### ISSUE TITLE
K8S(二)：实际使用-部署

### ISSUE THREAD

**Issue by MikasaLevi** [MikasaLevi/mydata#31]
# 前言

这篇文章背景：作者刚接触 K8S，之前做过相关的 SRE 工作，但是不是用 K8S 这一套，新项目上准备用 K8S，但还没有实际工作经验。这篇文章主要是整理一下非常基础的点，后续项目上用到了再补充更新一下。0.1 版本吧。

# 基本命令

这里可以看到 kubuctl 的一些命令：

![image](https://user-images.githubusercontent.com/35925768/61057025-08cf6480-a427-11e9-9aaf-d46b27a6ee01.png)

那么怎么部署，参考 [kubernetes - kubectl run vs create and apply](https://stackoverflow.com/questions/48015637/kubernetes-kubectl-run-vs-create-and-apply)

这里会有几种方式：

## 1. `kubectl run` + `kubectl expose` 组合

`kubectl run` 会创建并运行一个或者多个容器镜像，并且会创建一个 deployment 或者 job 来管理容器。

![image](https://user-images.githubusercontent.com/35925768/61057039-11279f80-a427-11e9-8ae5-a43aae6cafbd.png)

可以看到 `kubectl run` 一个镜像的时候，可以指定它暴露的端口，副本数等等。注意这个端口是镜像，容器的端口，而不是对外暴露服务的端口。（当然也可以通过 `-f` 指定文件配置）

`kubectl expose` 则会把资源暴露为新的 k8s service。因为上述的命令指示创建镜像，暴露的也是暴露该docker 的想象，那么要真正的给外部使用，还需要配置成 k8s 的服务，然后外部用户使用该 k8s 服务，k8s 再通过上述的容器端口，访问到真正的app。

## 2. `kubectl create`

create 命令用于创建集群资源。什么是集群资源，简单来说就是配置多少台服务器，多少个pod，docker的镜像是什么，端口是什么等等，也就是我们的配置的 yml 或者 json 文件。

所以首先会 `kubectl create -f filename` 创建出资源。`-f` 就表示 `--filename=[]`使用文件配置的意思。

## 3. `kubectl apply`

和 `kubectl create` 类似，但是 `kubectl create` 如果在资源存在的情况下，会抛错，`kubectl apply`则会更新。

# 综上

所以最后直接使用 `kubectl apply` 即可，没有资源就创建，有就更新。

# yml 文件

这里直接拉一份文件出来，一个个字段看，参考：

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uuid-name
  namespace: uuid-namspace
  labels:
    app: uuid-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxx
  template:
    metadata:
      labels:
        app: xxx
    spec:
      containers:
      - name: xxx
        image: notification.xxx.com/xxx:{{imageTag}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
      imagePullSecrets:
      - name: welabdemo
```

- apiVersion：k8s 的版本，参考 [K8S的apiVersion该用哪个](https://segmentfault.com/a/1190000017134399)
- kind：想要创建的对象的类型，比如说有 Deployment类型，有 Pod 类型等
- metadata：这个对象的唯一表示。
- metadata.name：这个对象的名字。
- metadata.namespace：这个对象所在的命名空间。不同的命名空间类似于不同的环境。
- metadata.labels：`Labels are key/value pairs that are attached to objects`，参考 [Kubernetes基本概念之Label](https://www.jianshu.com/p/cd6b4b4caaab)，也就是说，可以给这个资源打上标签，后续就可以根据这个进行筛选。
- spec：`The spec, which you must provide, describes your desired state for the object–the characteristics that you want the object to have. `
- replicas：副本的数量
- selector：`The selector field defines how the Deployment finds which Pods to manage`
- spec.template：.spec.template 是 .spec中唯一要求的字段。它指定了 Pod。
- template.metadata.labels：这个 Pod 的label。
- template.spec.containers：在它上面跑的 container。
- 然后就是 container 的名字，镜像，环境变量，秘钥得等的配置。

# 最后

最后 `kubectl apply -f xxx.yml` 即可 docker 部署。当然，在这之前还要 ：

1. docker 打包应用成镜像
2. 注意使用 `rolling update` 滚动更新。
