### ISSUE TITLE
CICD 流程：GitLab->ArgoCD->K8S 搭建(一)

### ISSUE THREAD

**Issue by MikasaLevi** [MikasaLevi/mydata#41]
# 前言

这里的CI/CD整体架构如下所示：

![image](https://user-images.githubusercontent.com/35925768/78472545-656c6f80-776c-11ea-8857-ee23bd5572ec.png)

总的来说，会涉及到几个方面的知识：

1. GitLab `.gitlab-ci.yaml` 文件，GitLab Runner 的配置。
2. Helm，Chart 相关
3. Argo CD 相关
4. K8S 相关。

# GitLab `.gitlab-ci.yaml`

参考： [segmentfault - 开始使用GitLab CI/CD](https://segmentfault.com/a/1190000012989919)，这里介绍了这个文件的基本背景。例如，我的测试的 `.gitlab-ci.yaml` 文件：

```
stages:
  - .pre
  - build
  - test
  - deploy
  - .post

pre_job:
  stage: .pre
  script:
    - echo "hello world - pre job"

build_job:
  stage: build
  script:
    - echo "hello world - build job"

test_job:
  stage: test
  script:
    - echo "hello world - test job"

deploy_job:
  stage: deploy
  script:
    - echo "hello world - deploy job"

post_job:
  stage: .post
  script:
    - echo "hello world - post job"
```

最后就变成了：

![image](https://user-images.githubusercontent.com/35925768/78472549-70270480-776c-11ea-9e47-7445db745d15.png)

这样我们就可以在不同的阶段做不同的事情，例如 build 阶段就是 `mvn install`，test 阶段就是跑测试用例，deploy 阶段就做一些部署，比如说 docker push 的事情等等。

这些配置好之后，我们的每次 push 代码，都会跑这个流程。所以就能够达到 CI 的这个目的。

# GitLab Runner

可以参考官方文档：[GitLab Runner Docs](https://docs.gitlab.com/runner/)，或者你的 GitLab 项目 -> Settings -> CI /CD -> Runner，总之，Runner 就是

> Runners are processes that pick up and execute jobs for GitLab

就像 [segmentfault - 开始使用GitLab CI/CD](https://segmentfault.com/a/1190000012989919) 说到的，你既可以用 docker， 也可以用虚拟机，也可以结合 K8S 跑你的 job，都可以。既有私有的，自己配置的，也有共有的，共享的。

这里我们本地测试可以不配置，默认用共享的就好了。后续可以再在生产或者实际项目中用私有的，自己配置的。

# 实际应用

上述说的一些都是非常非常基础的，实际中会稍微复杂一点。例如 `.gitlab-ci.yaml` 文件，你还需要关心一些东西是如何配置的，参考官方的配置说明：[GitLab CI/CD Pipeline Configuration Reference](https://docs.gitlab.com/ee/ci/yaml/)，例如说下面这些我觉得是需要稍微关心一下的：

![image](https://user-images.githubusercontent.com/35925768/78472555-79b06c80-776c-11ea-81f9-325da73bdb7e.png)

![image](https://user-images.githubusercontent.com/35925768/78472560-82a13e00-776c-11ea-919e-267f2b9c7f6b.png)

这里稍微解释下：

1. `script`：你的 job 要执行的命令，没啥好解释的。
2. `image`：就是你的 Runner 要执行的 job，需要的一些命令可能没有，所以就要用docker镜像，让你的 Runner 有这个命令。例如说，你要执行 `mvn install`，那本身你都没有装maven，所以这里可能就要引入 `image: maven:3.6.1-jdk-11-slim`，这样你才能执行这个命令。
3. `services`：这个参考:[What is the difference between Docker Service and Docker Container?](https://stackoverflow.com/questions/43408493/what-is-the-difference-between-docker-service-and-docker-container)，属于这部分的相关知识。（我也忘了，又涉及 docker swarm 啥的）
4. `stages`：你的 CI 的整个大流程的定义，没啥好解释的。
5. `stage`：表明你的 job 是属于哪个流程的。
6. `only`：这个比较有用，可以指明哪个分支要跑这个 job
7. `when`：可以指明手动还是自动触发这个 job。（这个也有用的，例如说部署 sit，stable 环境等等一些比较重要的环境，我们还是希望不要太自动化，需要人工再确认一下影响，确认后，再点一下再部署）
8. `artifacts`：页面UI 上可以下载一下这个 job 的运行后产物，这样就可以验证一下
9. `retry`：job 失败后自动重试一下。
10. `include`：类似 Java 的 Import
11. `extends`：类似 Java 的继承
12. `variables`：例如配置数据库的url，账号密码这些就需要到。

综上，所以说，稍微贴近实际一定的 `.gilab-ci.yaml` 文件可能就是这个样子的：

PS：这里以下很多细节实现上我就暂时不管了，需要的时间太多了，这里先了解下整体流程，和关键点先。

## `.pre` 流程

一般我们都是在本地分支开发，然后在合并到 develop 分支或者 master 分支的时候，我们希望你的合并遵守一定的规范，比如说，

1. link 关联你的需求（这里可能是 JIRA 或者是什么 URL 之类的）
2. 合并的 title，comment 遵守一定的规范。
3. 代码风格上是ok的。经过 sonar 检查。

满足上述的基本的 "外在形象" 的要求，才能进行后续的 build, test 这些 "内在" 的检测。

参考：[GitLab Docs -> Contributor and Development Docs -> Danger bot](https://docs.gitlab.com/ee/development/dangerbot.html)，GitLab 自己引入了 [GitHub - danger](https://github.com/danger/danger) 来做这些事情，这里可以自己弄一个关于 danger 的image。

```
danger_job:
  image: xxx
  stage: .pre
  script:
    - xxx
  only:
    - merge_requests
  retry: 2
```

关于 sonar 的，网上也有很多，当然有一种方式可以是参考：[SonarScanner for Maven](https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-maven/)

1. 项目代码 pom.xml 引入 sonar。
2. 利用 `mvn clean verify sonar:sonar` 命名。

## `build` / `test` 流程

这里关键就是 `mvn install`。 但是这里要注意两点，1个是本身没有 mvn 命名，2是 mvn install 后的 jar 包，如果传输到后续步骤中。

另外，其实 `mvn install` 就包含了 test 的流程，所以其实可以把 `build` 和 `test` 的步骤合并到一起。这里就可以类似这样：

```
build_and_test_job:
  image: maven:3.6.1-jdk-11-slim
  stage: buildandtest
  script: mvn install 
  services:
    - mysql
  variables:
    mysql_db: xxx
    mysql_user: xxx
    mysql_password: xxx
  artifacts:
    paths:
      - target/${PROJECT_NAME}-1.0.0-SNAPSHOT.jar
```

## docker hub

test 完成后，就可以docker 打包项目 image 到类似 docker hub 上了。等待后续部署。

## deploy 流程

deploy 流程，我们就可以如上述架构图所示，修改项目B的代码即可，主要把 commit 版本号换掉。例如：

```
deploy_job:
  when: manual
  image: alpine/git
  stage: deploy
  script:
    - git config --global user.email xxx
    - git config --global user.name xxxx
    - git clone xxx
    - update_commit_sha.sh
    - git add
    - git commit
    - git push
  only:
    - develop
```

就类似这样子。这样，整个 `.gitlab-ci.yaml` 的流程，所做的工作就差不多了。

# 遇到的比较大的问题

### CI Pipeline 慢

这里主要有2个原因：

1. Stages 比较多。要知道，这个 Stages 是串行执行的。
2. Runner 资源不够。这个是用来跑 job 的。这个资源不够，相当于 job 的执行要等，那整个流程就要等了。 

所以这里在设置 Pipeline，在编写 `.gitlab-ci.yaml` 的时候，需要注意：

1. 物理上多配置几个 Runner，多加一些资源。
2. 在合理的基础上，尽量减少 stages 大流程，合并到一个 stage 里，用不同的 job 并发来做。

# 总结

这篇文章主要介绍了绿框中的东西，后续再介绍下 Argo CD 和 K8S。

![image](https://user-images.githubusercontent.com/35925768/78472566-89c84c00-776c-11ea-9b17-cf0245450120.png)
